#!/bin/sh
# Run lint
echo "Running check..."
npm run check
LINT_RESULT=$?

if [ $LINT_RESULT -ne 0 ]; then
    echo "❌ Check failed. Please fix the issues before pushing."
    exit 1
fi

echo "✅ All checks passed!"
exit 0
